version: '3'
services:
  app:
    build: ./app
    volumes:
      - /vagrant/tutorial:/srv/www
      - /var/log:/var/log
    links:
      - db
  db:
    build: ./db
    env_file:
      - "db/db.env"
    volumes:
      - /var/lib/postgres/data:/var/lib/postgres/data
  web:
    build: ./web
    volumes:
      - /vagrant:/srv/www
      - /var/log/nginx:/var/log/nginx
    ports:
      - "8000:8000"
    links:
      - app
